ci:
    autofix_prs: false
repos:
  - repo: local
    hooks:
      # Prevent committing .rej files from copier
      - id: forbidden-copier-rej-files
        name: forbidden copier rej files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: \.rej$

  - repo: local
    hooks:
      # Prevent committing test.py files within the tests directory
      - id: forbidden-testpy-files
        name: forbidden testpy files
        entry: found test.py file inside tests directory; rename or remove them
        language: fail
        files: ((./tests/.*/test.py)|(./tests/test.py))$

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

  - repo: local
    hooks:
      - id: uv-lock
        name: uv-lock
        entry: uv lock --offline
        files: ^(uv\.lock|pyproject\.toml|uv\.toml)$
        additional_dependencies:
          - uv==0.8.3
        language: python
        always_run: true
        pass_filenames: false
      - id: uv-sync
        name: uv-sync
        entry: uv sync --no-active --offline
        args: [--locked]
        additional_dependencies:
          - uv==0.8.3
        language: python
        always_run: true
        pass_filenames: false
        stages: [manual, pre-commit, pre-push, post-checkout, post-merge, 
                post-rewrite]
      - id: uv-export
        name: uv-export
        files: ^uv\.lock|requirements.txt$
        entry: uv export --frozen --offline --quiet --no-default-groups 
            -o="requirements.txt"
        additional_dependencies:
          - uv==0.8.3
        language: python
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.4.1
    hooks:
      - id: ensure-dunder-all
        files: .*/__init__\.py$
        exclude: tests/assets/

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        always_run: true
        entry: uv run --frozen --offline ruff format --force-exclude
        types_or: [python, pyi, jupyter]
        additional_dependencies:
          - uv==0.8.3
        language: python
        pass_filenames: false
      - id: ruff-check
        name: ruff-check
        always_run: true
        entry: uv run --frozen --offline ruff check --fix  --force-exclude 
            --ignore "FIX"
        types_or: [python, pyi, jupyter]
        additional_dependencies:
          - uv==0.8.3
        language: python
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=100000]
      - id: trailing-whitespace
        exclude: (.*\.sh|.*\.d2|.*\.md|.*\.drawio|.*egg-info.*|)$
      - id: check-merge-conflict
        args: [--assume-in-merge]

  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout
        entry: uv run --frozen --offline nbstripout
        additional_dependencies:
          - uv==0.8.3
        language: python
        files: .*\.(ipynb)$
        exclude: .*\.(example|template|keepoutput|)\.ipynb$

  - repo: local
    hooks:
      - id: deptry
        name: deptry
        entry: uv run --frozen --offline deptry src
        additional_dependencies:
          - uv==0.8.3
        language: python
        always_run: true
        pass_filenames: false
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run --frozen --offline pyright
        additional_dependencies:
          - uv==0.8.3
        language: python
        types_or: [python, pyi]
        always_run: true
        require_serial: true
default_install_hook_types:
  - pre-commit
  - pre-push
  - post-checkout
  - post-merge
  - post-rewrite
default_stages:
  - pre-commit
  - pre-push
