
name: Release to PyPI
permissions:
  contents: read
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
        - name: Checkout code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Set up uv
          uses: astral-sh/setup-uv@3b9817b1bf26186f03ab8277bab9b827ea5cc254 # v3.2.0
          with:
            version: "0.8.3" # Sync with pyproject.toml

        - name: "Set up Python"
          uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
          with:
            python-version: 3.13

        - name: Release
          run: |
            uv build
            uv publish --trusted-publishing always